name: test

on:
   push:
      branches: [master, fix_ci]
   pull_request:
      branches: [master]

env:
   CARGO_TERM_COLOR: always

jobs:
   test:
      runs-on: ubuntu-latest

      steps:
         - name: Install dependencies
           run: sudo apt-get install libpango
         - name: Set up
           uses: actions-rs/toolchain@v1
           with:
              toolchain: nightly
              override: true
              components: rustfmt

         - uses: actions/checkout@v2
         - name: Test
           run: cargo test --verbose
